basePath: /
host: 127.0.0.1:8000
info:
  contact: {}
  description: This is a sample server.
  title: My API
  version: "1.0"
paths:
  /result/{task_id}:
    get:
      description: Post task_id in DataBase
      parameters:
      - description: task_id
        in: path
        name: task_id
        required: true
        type: string
      responses:
        "200":
          description: 'result": "result state'
          schema:
            type: json
        "404":
          description: Failed to get result
          schema:
            type: string
      summary: Get task result
  /status/{task_id}:
    get:
      description: Post task_id in DataBase
      parameters:
      - description: task_id
        in: path
        name: task_id
        required: true
        type: string
      responses:
        "200":
          description: 'status": "status state'
          schema:
            type: json
        "404":
          description: Failed to get status
          schema:
            type: string
      summary: Get task status
  /task:
    post:
      description: Post task_id in DataBase and start task
      responses:
        "201":
          description: 'task_id": "id value'
          schema:
            type: json
        "404":
          description: Failed to store value
          schema:
            type: string
      summary: Post task task_id
swagger: "2.0"
